### ISSUE TITLE
Deployment of WVD Management UX Fails

### ISSUE THREAD

**Issue by QuiggUK** [Azure/RDS-Templates#187]
Hello,

I am attempting to deploy the Management UI to my Azure Subscription however it seems to be failing on the last step.

Below is a snippet from the failure log

OPERATION ID  BC39EDEA53B95574
TRACKING ID  7e48d156-ed95-4068-9a08-ebd691239a24
STATUS  Conflict
STATUS MESSAGE  {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'."
  }
}
PROVISIONING STATE  Failed
TIMESTAMP  10/07/2019, 22:55:26
DURATION  1 minute 20 seconds
TYPE  Microsoft.Automation/automationAccounts/jobs
RESOURCE ID  /subscriptions/dc507527-9d62-49e0-b3db-4d118901d7f9/resourceGroups/SkancoTechWVD-WebManangement/providers/Microsoft.Automation/automationAccounts/wvdsaas-autoAccount-idmugyytcmw2q/jobs/8e110029-cc79-5d30-89fe-a52a1921b52f
RESOURCE  wvdsaas-autoAccount-idmugyytcmw2q/8e110029-cc79-5d30-89fe-a52a1921b52f

**Comment by ChristianMontoya** [comment]
@QuiggUK : Though it failed, were you able to connect and logon to the management UX?

**Comment by ptgadmin-cse** [comment]
@QuiggUK: We have pushed latest build to Github. Can you please deploy one more time with new instance and let me know if you have facing any issue.

**Comment by TETZUO** [comment]
> @QuiggUK: We have pushed latest build to Github. Can you please deploy one more time with new instance and let me know if you have facing any issue.

Still fails
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"The name Azure Virtual Desktop mangement UX-SPlan is not valid.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"The name Azure Virtual Desktop mangement UX-SPlan is not valid.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"ExtendedCode\": \"01003\",\r\n \"MessageTemplate\": \"The name {0} is not valid.\",\r\n \"Parameters\": [\r\n \"Azure Virtual Desktop mangement UX-SPlan\"\r\n ],\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"The name Azure Virtual Desktop mangement UX-SPlan is not valid.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"}]}

**Comment by ptgadmin-cse** [comment]
@QuiggUK : I hope you are provided ApplicationName parameter value with spaces in custom deployment. So template is validated and got this error. For your reference please find the below highlighted. Can you please provide ApplicationName parameter value without spaces (Ex. "WVDmgmtUx-App" ) and let me know if you have facing any issue.

Still fails
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n "Code": "BadRequest",\r\n "Message": "The name Azure Virtual Desktop mangement UX-SPlan is not valid.",\r\n "Target": null,\r\n "Details": [\r\n {\r\n "Message": "The name Azure Virtual Desktop mangement UX-SPlan is not valid."\r\n },\r\n {\r\n "Code": "BadRequest"\r\n },\r\n {\r\n "ErrorEntity": {\r\n "ExtendedCode": "01003",\r\n **"MessageTemplate": "The name {0} is not valid.",\r\n "Parameters": [\r\n "Azure Virtual Desktop mangement UX-SPlan"\r\n ],\r\n "Code": "BadRequest",\r\n "Message": "The name Azure Virtual Desktop mangement UX-SPlan is not valid."**\r\n }\r\n }\r\n ],\r\n "Innererror": null\r\n}"}]}

**Comment by QuiggUK** [comment]
I couldn’t.

I think I may have found the issue.

My azure subscription and Office 365 tenant were using separate Azure AD instances (due to licenses needs). I have moved my Office 365 items into the Azure AD tenant, restarted the WVD deployment prereqs, and now it deploys/works fine.

Thanks
Ryan

**Comment by ChristianMontoya** [comment]
@QuiggUK : Glad to hear. Please let us know if there are any other issues!

**Comment by TETZUO** [comment]
> @TETZUO : I hope you are provided ApplicationName parameter value with spaces in custom deployment. So template is validated and got this error. For your reference please find the below highlighted. Can you please provide ApplicationName parameter value without spaces (Ex. "WVDmgmtUx-App" ) and let me know if you have facing any issue.
> 
> Still fails
> {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n "Code": "BadRequest",\r\n "Message": "The name Azure Virtual Desktop mangement UX-SPlan is not valid.",\r\n "Target": null,\r\n "Details": [\r\n {\r\n "Message": "The name Azure Virtual Desktop mangement UX-SPlan is not valid."\r\n },\r\n {\r\n "Code": "BadRequest"\r\n },\r\n {\r\n "ErrorEntity": {\r\n "ExtendedCode": "01003",\r\n **"MessageTemplate": "The name {0} is not valid.",\r\n "Parameters": [\r\n "Azure Virtual Desktop mangement UX-SPlan"\r\n ],\r\n "Code": "BadRequest",\r\n "Message": "The name Azure Virtual Desktop mangement UX-SPlan is not valid."**\r\n }\r\n }\r\n ],\r\n "Innererror": null\r\n}"}]}

That worked fine with no spaces, can the template be updated to prompt the admin that spaces are not supported?
